# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
#enable jupyter extensions
!jupyter nbextension enable --py --sys-prefix widgetsnbextension
# jupyter nbextension enable --py widgetsnbextension
!install gmaps 
# conda install -c conda-forge gmaps 

# enable gmaps
!jupyter nbextension enable --py --sys-prefix gmaps

Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: ok
install: missing destination file operand after 'gmaps'
Try 'install --help' for more information.
Enabling notebook extension jupyter-gmaps/extension...
      - Validating: ok

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import gmaps
import pandas as pd
import requests


# Google developer API key
from api_keys import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [3]:
weather_csv_file = "../output_data/weather_data.csv"
weather_df = pd.read_csv(weather_csv_file)
weather_df.dropna()
weather_df.head()

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Qaanaaq,77.48,-69.36,47.41,53,0,8.81,GL,1595794573
1,1,Kotri,25.37,68.31,89.24,62,2,15.08,PK,1595794778
2,2,Butaritari,3.07,172.79,83.39,74,1,14.81,KI,1595794517
3,3,Ushuaia,-54.80,-68.30,33.80,90,75,23.04,AR,1595794235
4,4,Mae Chan,20.15,99.85,77.00,94,100,4.70,TH,1595794782

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:
locations = weather_df[["Lat", "Lng"]]
humidity = weather_df["Humidity"].astype(float)
fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=max(humidity),
                                 point_radius=3)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [6]:
idealWeather_df = weather_df.loc[(weather_df['Cloudiness'] == 0) &
                                 (weather_df['Max Temp'] < 80) &
                                 (weather_df['Max Temp'] > 70) &
                                 (weather_df['Wind Speed'] < 10)]

idealWeather_df = idealWeather_df.dropna()
idealWeather_df.head()

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
24,24,Palpa,-14.53,-75.19,78.93,31,0,8.81,PE,1595794804
70,70,Sciacca,37.51,13.09,75.99,65,0,7.00,IT,1595794857
147,147,Safi,32.30,-9.24,72.01,88,0,9.33,MA,1595794946
230,230,Muros,42.78,-9.06,73.00,64,0,6.93,ES,1595795041
307,307,Vic,41.93,2.25,73.99,79,0,2.66,ES,1595795128

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [7]:
# Code from "NearestRestr" heavily referenced to complete the hotel map section, and some hints from Bob
hotel_df = idealWeather_df

#params dictionary to update each iteration
params = {"radius": 5000,
    "type": "lodging",
    "key": g_key}

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# use iterrows to iterate through pandas dataframe
for index, row in hotel_df.iterrows():

#get coordinates from df
    lat = row["Lat"]
    lng = row["Lng"]

# add keyword to params dict
    params["location"] = f"{lat},{lng}"
    
# assemble url and make API request
    print(f"Retrieving Results for Index {index}: {row['City']}.")
    response = requests.get(base_url, params=params).json()
    response
    # extract results
    results = response['results']
    
    try:
        print(f"{results[0]['name']} is the nearest hotel.")
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")

Retrieving Results for Index 24: Palpa.
Palpa Lines is the nearest hotel.
------------
Retrieving Results for Index 70: Sciacca.
Hotel Aliai is the nearest hotel.
------------
Retrieving Results for Index 147: Safi.
Hôtel Abda is the nearest hotel.
------------
Retrieving Results for Index 230: Muros.
Apartment Av. Castelao is the nearest hotel.
------------
Retrieving Results for Index 307: Vic.
Up Rooms Vic Hotel ® - WEB OFICIAL is the nearest hotel.
------------
Retrieving Results for Index 309: Bayir.
Buban Otel is the nearest hotel.
------------
Retrieving Results for Index 368: Shīeli.
Gostinitsa Aybek Shieli is the nearest hotel.
------------
Retrieving Results for Index 370: Burns Lake.
Burns Lake Bed and Breakfast is the nearest hotel.
------------
Retrieving Results for Index 374: Tongzi.
Missing field/result... skipping.
------------
Retrieving Results for Index 382: Porto Torres.
Hotel Elisa is the nearest hotel.
------------
Retrieving Results for Index 439: Tiznit Province.
Missing field/result... skipping.
------------
Retrieving Results for Index 455: Sumbe.
Hotel Ritz Sumbe is the nearest hotel.
------------
Retrieving Results for Index 466: Vila.
Hotel Castrum Villae is the nearest hotel.
------------
Retrieving Results for Index 490: Lusambo.
Missing field/result... skipping.
------------
Retrieving Results for Index 532: Médéa.
Hôtel M'Sallah is the nearest hotel.
------------

In [8]:
hotel_df = hotel_df.dropna()
hotel_df

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
24,24,Palpa,-14.53,-75.19,78.93,31,0,8.81,PE,1595794804,Palpa Lines
70,70,Sciacca,37.51,13.09,75.99,65,0,7.00,IT,1595794857,Hotel Aliai
147,147,Safi,32.30,-9.24,72.01,88,0,9.33,MA,1595794946,Hôtel Abda
230,230,Muros,42.78,-9.06,73.00,64,0,6.93,ES,1595795041,Apartment Av. Castelao
307,307,Vic,41.93,2.25,73.99,79,0,2.66,ES,1595795128,Up Rooms Vic Hotel ® - WEB OFICIAL
309,309,Bayir,37.27,28.22,75.20,69,0,3.94,TR,1595795130,Buban Otel
368,368,Shīeli,44.17,66.75,76.91,28,0,8.05,KZ,1595795199,Gostinitsa Aybek Shieli
370,370,Burns Lake,54.23,-125.75,77.34,35,0,6.22,CA,1595795201,Burns Lake Bed and Breakfast
382,382,Porto Torres,40.84,8.40,77.00,65,0,4.70,IT,1595795215,Hotel Elisa
455,455,Sumbe,-11.21,13.84,70.21,87,0,6.69,AO,1595795299,Hotel Ritz Sumbe
466,466,Vila,42.03,-8.16,78.01,54,0,3.00,PT,1595795312,Hotel Castrum Villae
532,532,Médéa,36.26,2.75,78.80,78,0,6.93,DZ,1595795388,Hôtel M'Sallah

In [9]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [10]:
hotel_name = hotel_df["Hotel Name"].tolist()

In [11]:
# Referenced "Census_States" exercise to create this code

locations = weather_df[["Lat", "Lng"]]
humidity = weather_df["Humidity"].astype(float)
marker_locations = hotel_df[['Lat', 'Lng']]

fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=max(humidity),
                                 point_radius=3)

markers = gmaps.marker_layer(marker_locations,
    info_box_content=[f"{list}" for list in hotel_name])


fig.add_layer(heat_layer)
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))